# Generated by Django 5.1 on 2024-09-03 19:29

import django.db.models.deletion
import item.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(default=40)),
                ('image', models.ImageField(upload_to=item.models.upload_location)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stars', models.IntegerField(default=4)),
                ('category', models.CharField(choices=[('featured', 'Featured'), ('popular', 'Popular'), ('recommended', 'Recommended'), ('favorate', 'Favorate')], default='popular', max_length=20)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
            options={
                'ordering': ['updated', 'created', 'id'],
            },
        ),
    ]
