# Generated by Django 5.1 on 2025-01-08 07:11

import item.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to=item.models.upload_location),
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to=item.models.upload_location),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to=item.models.upload_location),
        ),
    ]
