# Generated by Django 5.1 on 2025-01-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_image_alter_item_image1_alter_item_image2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-updated', '-created', 'id']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
    ]
