openapi: 3.0.3
info:
  title: Multi Tenant
  version: 1.0.0
  description: Your project description
paths:
  /:
    get:
      operationId: root_retrieve
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /item/food/{id}/:
    get:
      operationId: item_food_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - item
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /item/food/{id}/update/:
    put:
      operationId: item_food_update_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - item
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /item/food/recommended:
    get:
      operationId: item_food_recommended_retrieve
      tags:
      - item
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /item/food/search:
    get:
      operationId: item_food_search_retrieve
      tags:
      - item
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /item/shops/allitems:
    get:
      operationId: item_shops_allitems_retrieve
      tags:
      - item
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /item/shops/items:
    post:
      operationId: item_shops_items_create
      tags:
      - item
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /user/:
    post:
      operationId: user_create
      tags:
      - user
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /user/login:
    post:
      operationId: user_login_create
      tags:
      - user
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /user/viewUsers:
    get:
      operationId: user_viewUsers_retrieve
      tags:
      - user
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
