# Generated by Django 5.1 on 2024-09-04 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoprole',
            name='shop_role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.role'),
        ),
    ]
