# Generated by Django 5.1 on 2025-01-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roles',
            unique_together={('name', 'shop')},
        ),
    ]
