# Generated by Django 5.1 on 2025-02-22 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_roles_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
    ]
