# Generated by Django 5.1 on 2024-09-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('shop', '0002_alter_shoprole_shop_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoprole',
            unique_together={('shop_role', 'shop')},
        ),
    ]
