# Generated by Django 5.1 on 2024-09-04 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('shop', '0003_alter_shoprole_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoprole',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='shoprole',
            name='shop_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.role'),
        ),
        migrations.AddConstraint(
            model_name='shopuser',
            constraint=models.UniqueConstraint(fields=('shop', 'user'), name='unique_user_per_shop'),
        ),
    ]
