# Generated by Django 5.1 on 2025-02-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderduration',
            name='time',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
