# Generated by Django 5.1 on 2025-03-05 09:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_orderduration_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopuser',
            unique_together={('user', 'shop')},
        ),
    ]
