# Generated by Django 5.1 on 2025-01-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_orderitem_order_remove_orderitem_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
