# Generated by Django 5.1 on 2025-01-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_orderitem_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
