# Generated by Django 5.1 on 2024-08-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_test'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table='test',
        ),
    ]
