# Generated by Django 5.1 on 2024-08-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_permission_table_alter_role_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
